forge 'https://forge.puppet.com'

mod 'puppetlabs-puppet_operational_dashboards', '2.3.0'
mod 'puppet-grafana', '13.2.0'
mod 'puppet-archive', '7.1.0'
mod 'puppet-telegraf', '5.4.0'
mod 'puppetlabs-stdlib', '9.6.0'
mod 'puppetlabs-inifile', '6.1.1'
mod 'puppetlabs-influxdb', '2.4.0'
mod 'puppetlabs-apt', '9.4.0'
